#!/usr/bin/env python3
"""Check that every object reference in a project.pbxproj resolves to a defined object.

A pbxproj is a graph of 24-hex-digit object IDs. Xcode does not tolerate a dangling one: a
single unresolved reference makes it refuse the whole project with

    The project 'X' is damaged and cannot be opened.
    Exception: The project contains no build configurations - it may have been damaged

which names no file, line, or ID. Since this project's pbxproj is machine-generated by
iosApp/generate-project.py, a bug there silently produces a file that looks plausible and
fails only on a macOS runner, minutes into a release build. This script catches it on Linux
in milliseconds.

Usage: verify-xcodeproj.py <path to project.pbxproj>
"""
import re
import sys

ID = re.compile(r"\b[0-9A-F]{24}\b")
# An object definition: `\t\t<ID> /* comment */ = {` or `\t\t<ID> = {`
DEFINITION = re.compile(r"^\s*([0-9A-F]{24})\b[^=]*=\s*\{")


def main(path):
    try:
        with open(path, encoding="utf-8") as handle:
            lines = handle.readlines()
    except OSError as exc:
        print(f"error: cannot read {path}: {exc}")
        return 2

    defined = set()
    for line in lines:
        match = DEFINITION.match(line)
        if match:
            defined.add(match.group(1))

    if not defined:
        print(f"error: {path} declares no objects at all — is it a pbxproj?")
        return 1

    # Every ID mentioned anywhere that is not a definition site is a reference.
    dangling = {}
    for number, line in enumerate(lines, start=1):
        definition = DEFINITION.match(line)
        for found in ID.findall(line):
            if definition and found == definition.group(1):
                continue
            if found not in defined:
                dangling.setdefault(found, []).append((number, line.strip()))

    # An .xcframework is a container of per-slice .framework bundles. Declared as
    # wrapper.framework, Xcode silently skips the ProcessXCFramework step that resolves the
    # slice, and the build dies much later at `error: no such module 'X'` — which points at
    # the import, not at the project file that actually caused it.
    mistyped = []
    for number, line in enumerate(lines, start=1):
        if ".xcframework;" in line and "isa = PBXFileReference" in line:
            if "wrapper.xcframework" not in line:
                mistyped.append((number, line.strip()))

    if mistyped:
        print(f"FAIL: {path}")
        print("  .xcframework reference(s) not declared as wrapper.xcframework:\n")
        for number, text in mistyped:
            print(f"  line {number}: {text[:140]}")
        print("\nThis surfaces at build time as \"no such module\", far from the real cause.")
        return 1

    if dangling:
        print(f"FAIL: {path}")
        print(f"  {len(defined)} objects defined, {len(dangling)} reference(s) resolve to nothing.\n")
        for ref, sites in sorted(dangling.items(), key=lambda kv: kv[1][0][0]):
            first_line, first_text = sites[0]
            if len(first_text) > 100:
                first_text = first_text[:100] + "..."
            print(f"  {ref}  line {first_line}: {first_text}")
        print("\nXcode reports this only as 'the project is damaged'. Regenerate with")
        print("iosApp/generate-project.py after fixing the ID wiring there.")
        return 1

    print(f"OK: {path} — {len(defined)} objects, every reference resolves.")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(2)
    sys.exit(main(sys.argv[1]))
