platform :ios, '14.0'

target 'iosApp' do
  use_frameworks!
  use_modular_headers!

  # Kotlin Multiplatform framework
  pod 'shared', :path => '../shared'

  target 'iosAppTests' do
    inherit! :search_paths
    pod 'Nimble', '~> 12.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'COCOAPODS=1'
      ]
    end
  end
end
